// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ClientForm: typeof import('./src/clients/components/ClientForm.vue')['default']
    Header: typeof import('./src/common/components/Header/header.vue')['default']
    Order: typeof import('./src/orders/components/Order.vue')['default']
    ProductForm: typeof import('./src/products/components/ProductForm.vue')['default']
    ReportForm: typeof import('./src/reports/components/ReportForm.vue')['default']
    SaleForm: typeof import('./src/sales/components/SaleForm.vue')['default']
    Sidenav: typeof import('./src/common/components/SideNav/sidenav.vue')['default']
    VButton: typeof import('./src/common/components/Button/v-button.vue')['default']
    VInfoModalWindow: typeof import('./src/common/components/Modal/v-info-modal-window.vue')['default']
    VInputSearch: typeof import('./src/common/components/Inputs/v-input-search.vue')['default']
    VInputText: typeof import('./src/common/components/Inputs/v-input-text.vue')['default']
    VModalWindow: typeof import('./src/common/components/Modal/v-modal-window.vue')['default']
    VModalWindows: typeof import('./src/common/components/Modal/v-modal-windows.vue')['default']
    VTable: typeof import('./src/common/components/Table/v-table.vue')['default']
  }
}

export { }
