// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/common/components/Header/header.vue')['default']
    Sidenav: typeof import('./src/common/components/SideNav/sidenav.vue')['default']
    VButton: typeof import('./src/common/components/Button/v-button.vue')['default']
  }
}

export { }
